### ISSUE TITLE
"Submit a Session" block is stale

### ISSUE THREAD

**Issue by ForestMars** [NYC-Camp/website#163]
Since session submissions are closed, this block is stale content. Instead it should be a call to action to register for the camp, along with a list of featured sessions. This of course is just a stop gap until we deploy the carousel, so doing that will close this issue. But if that is not going to happen today we should fix this block. 

Also we could just kill the "submit a session" block and use the "NYC Camp Updates" block instead.

**Comment by likewhoa** [comment]
do we have a way to show featured sessions? I don't recall there being a 'featured session?' field, if this is the case i can just make this field then a block after which filters by it so we can replace the submit a session block with it.

**Comment by ForestMars** [comment]
Y, we should probably add this field, since we're already touting our featured sessions / speakers in mailouts & social media.

**Comment by likewhoa** [comment]
i'll take care of this now and will reference the pr here.

**Comment by likewhoa** [comment]
The multidev for is at http://fr-frtsess-nyccamp2014.gotpantheon.com I have currently only made the block show [title] and [presenters] and set for any empty fields to not show up since the ones I picked didn't have any presenters. Anyways, set some featured sessions and test the view more.

My suggestions are to make block a single item carousel with [picture][title][presenters] instead of just an un-formatted block.

**Comment by ForestMars** [comment]
This looks fine, and is only a temp fix anyway until the carousel goes live. Please send PR.
