### ISSUE TITLE
No way to tell if registered

### ISSUE THREAD

**Issue by ForestMars** [NYC-Camp/website#165]
**Expected:** As a user I need to be able to see whether I am registered for this year's conference. 

This should be prominently displayed on my profile. 

**Actual:** I don't see any way to tell, as a test user, if I am registered or not. 

**Related:** As a user I need to be able to cancel my registration, if I am unable to attend for some reason.

**Comment by esod** [comment]
Truth be told, I don't even know if I'm registered. I mean that from the UX standpoint. I'll have a look.

**Comment by esod** [comment]
Are authenticated users registered?

**Comment by ForestMars** [comment]
> "Are authenticated users registered?"

Not for this year's camp, that is, not by default anyway. 

Just logging into the site doesn't register you to attend NYC Camp this year. I can promise you a LOT of people who have accounts on the site don't understand that. But that's messaging, not strictly implementation. 

For implementation we really just need a way for a user to see if / confirm they are registered to attend this year, and to cancel that registration if necessary.

**Comment by esod** [comment]
I've gotten past the blocker because of our implementation of Display Suite not having any layouts enabled without which no custom fields can be created. But I'm blocked because there doesn't seem to be an API for Entity Registration. The display suite code that would swap in a different block for a registered user would look something like this:

<code>
<?php
if(registration_is_registered($registration, NULL, $entity->uid)) {
views_embed_view('conference', 'block_1');
} else {
views_embed_view('conference', 'block');
}
?>
</code>

This snippet would use  the Display Suite Code text filter and would depend on another block display (block_1) which contains a registation status field with default text and the Registration field which prints the registration form. But I can't find a way to determine succinctly if a user is registered. 

Even if I could find or there is an API function, Display Suite prints in the content region and we want to swap this block in and out in the aside.

My preference, of course, is to write this snippet in a script file and not have it be contained in the database. But that's another matter.

The problem are
1. Find a way to determine succinctly if a user is registered.
2.  Swap in a different view accordingly.

**Comment by willykaram** [comment]
I think that the simple solution here is to write a view with relationship between registration and users, and pass in the user id as a contextual filter, should be manageable.

**Comment by esod** [comment]
I still don't see how I can get this done without the dreaded views_php module. But I'll have another look.

**Comment by willykaram** [comment]
Eric - I can do this quickly now. Is that ok?
- Willy

**Comment by ForestMars** [comment]
+1 for getting done quickly without views_php.

**Comment by esod** [comment]
https://github.com/NYC-Camp/website/pull/210

**Comment by likewhoa** [comment]
I believe #210 has resolved this issue. Thanks @esod
