### ISSUE TITLE
Why are event registrations coming from example@example.com

### ISSUE THREAD

**Issue by ForestMars** [NYC-Camp/website#181]
It appears that the from email address on all registration nodes (save the ones I've already changed) is set to example@example.com (see screenshot.) 

Thus is seems like a global setting got changed, since that was not the address used with registrations last year. 

In any case we need to change this so that all event registrations (Trainings, Summits & Sprints) come from info@nyccamp.org. (In the case of of summits, this could be set to summits@nyccamp.org, which would be preferable.) 

Note that the core summit is invite only (as is the security summit, I think.)

Example: http://www.nyccamp.org/node/548/registrations/settings

**Comment by likewhoa** [comment]
This default can be set at the field_registration on event content type. see admin/structure/types/manage/event/fields/field_registration. I have already set this default to info@nyccamp.org, but unfortunately this field's settings is in binary blob format inside the db table registration_entity, so we can't really just go ahead and do a mass search and replace of example@example.com to info@nyccamp.org to get all the existing nodes with the correct email for registration.

Someone will have to go through each event node to set this email accordingly afraik or run code to automate the process. 

Since cod has 'example@example.com' hardcoded in profiles/cod/modules/contrib/cod_support/cod_events/cod_events.features.field_instance.inc and imo it should instead default to the site's mail or sendmail_from setting in php.ini.

I am going to attach a patch upstream which will get rid of this hardcoded email and instead of site's mail or sendmail_from instead. I'll include a pr for us to use now so we don't have to wait for upstream.

Close issue at will.

**Comment by likewhoa** [comment]
I have contributed patch upstream at https://drupal.org/node/2222713. Also :+1: on quadruple 2's \o/

**Comment by esod** [comment]
The patch looks good to me. I think we can set a rule for existing event nodes

**Comment by esod** [comment]
I'll follow up with the rule.

**Comment by esod** [comment]
I can't reach the From Address field with a rule. I'll go through the existing events and change them to info@nyccamp.org

**Comment by likewhoa** [comment]
thanks @esod. closing :+1:
