### ISSUE TITLE
Summit acceptance email should indicate *which* summit

### ISSUE THREAD

**Issue by ForestMars** [NYC-Camp/website#202]
When a submitted session is accepted for inclusion in one of the summits, an email is sent by Rules to the submitter letting them know. 

This email should indicate which summit their session has been added to, which is a field on the session node ("which summit") 

This should be added by loading that field and and printing it in the email template that goes out in this rule: 

http://www.nyccamp.org/admin/config/workflow/rules/reaction/manage/rules_email_speaker_accepted_summit_session

**Comment by likewhoa** [comment]
I think we can consolidate all of these similar rules into one that can handle each specific condition,.

**Comment by likewhoa** [comment]
Ok I have consolidated the notification rules for event types into one so that our rules don't grow to big in the future. This new rule is also personalized to the given user and event type and I welcome suggestions and improvements on it.

My only suggestion now is to include the mime mail module on the site so that we can send HTML emails to users using these rules for a better way to link to the site.

The new rule which replaces:
- admin/config/workflow/rules/reaction/manage/rules_email_the_prospective_speaker_when_their_session_is_accept 
- admin/config/workflow/rules/reaction/manage/rules_email_the_prospective_speaker_when_their_training_is_accep
- admin/config/workflow/rules/reaction/manage/rules_email_the_prospective_speaker_when_their_training_is_sched
- admin/config/workflow/rules/reaction/manage/rules_email_speaker_accepted_summit_session

is located at http://fr-notfenc-nyccamp2014.gotpantheon.com/admin/config/workflow/rules/reaction/manage/rules_email_the_speaker_when_their_session_type_is_accept

Do review and let me know when approved, the only thing you need to do is delete the old rules above and export/import this one into live.

**Comment by likewhoa** [comment]
Closing,.. the following rule located at admin/config/workflow/rules/reaction/manage/rules_email_the_speaker_when_their_session_type_is_accept has replaced the 4 rules above.

**Comment by ForestMars** [comment]
We can defer improvements until post-camp, one thing I would say is that it needs to be more token driven, so "NYC Camp" isn't hard coded into the rule, but it references the default conference name. 

This follows from our goal of adding features that are useful to other camps, and easily usable out of the box.
