### ISSUE TITLE
Volunteer box remains unchecked on user profile page

### ISSUE THREAD

**Issue by mirie** [NYC-Camp/website#23]
This is still a problem. I'm creating this issue on github instead of tracking it in Trello so we can get more eyes on it.

Steps to recreate:
1. Create a test user and check the volunteer box
2. Login

You will see that the volunteer box under the newsletter subscription tab remains unchecked. This will remain unchecked even after confirming the mailchimp volunteer signup list (the mailchimp email is not immediate).

**Comment by tz-earl** [comment]
Mailchimp module issue: https://drupal.org/node/2173189

Unfortunately, there's not much detail in that issue, but it sounds like the same problem.

**Comment by jmarkel** [comment]
This problem seems to be resolved. There is a checkbox on each mailing list profile as to whether the subscriptions should be sent to MailChimp synchronously or via work-queue when cron runs. It looks from the code in the mailchimp module like the the user is being looked up via the MC API, but if the queue has not been run (which it may not have been) they still appear to not be a subscriber. Still not entirely sure if they EVER get added when the queueing method is operating.

One thing to note is that this checkbox (for Volunteer) is really only a mailing list subscription, not an item in the user's profile, which seems a little odd to me even if it works for our purposes - using it as an expression of interest in volunteering is kind of a side-effect of the list-subscription.

**Comment by ForestMars** [comment]
Not sure I follow here, but if I do get your meeting, queuing method is what I used last year, and it worked seamlessly.

**Comment by jmarkel** [comment]
Yeah, I've no doubt you're correct, Forest. But there have been various code changes since then. One issue seems to be the way subscriber info is being saved in the local cache. I'll trace it through more thoroughly when I have some time, but it's working now, which was the main problem for our immediate need.

**Comment by jmarkel** [comment]
Mai, I'm kicking this back to you to decide if you want to close it now.

**Comment by mirie** [comment]
I checked this on Sat and it looked good. I forgot to comment and close this out.
