### ISSUE TITLE
Getting spammed hard

### ISSUE THREAD

**Issue by ForestMars** [NYC-Camp/website#253]
We're getting spammed pretty hard, and they're activating their accounts. Here's just a recent sampling. 

![screen shot 2014-04-03 at 11 16 54 pm](https://cloud.githubusercontent.com/assets/402773/2611577/bb93c02a-bba7-11e3-8c66-a22721c8f4d3.png)

**Comment by mirie** [comment]
Hey @ForestMars , what's the best way to fix this? We have email verification enabled for new accounts and also a captcha.

**Comment by likewhoa** [comment]
@ForestMars @mirie http://dgo.to/mollom will take care of this.

**Comment by likewhoa** [comment]
guys my internet connection to my irssi server is being crappy, so do communicate here. I can get mollom rolling on the site now.

**Comment by mirie** [comment]
Ha. ok that explains why u're no responding to me in the channel. Okie doke.

**Comment by likewhoa** [comment]
oh guys, we already have mollom on the site, and seeing how we only have captcha as our only defense against automated registrations which most bots defeat and since we only have 3-4 fields that users need to fill out with only first/last being required, there is no reason to set the form to 'text analysis' we really need to think of something else to stop these spam bots.

**Comment by esod** [comment]
Honeypot?

**Comment by likewhoa** [comment]
:+1: for testing honeypot but lets do that after the camp.

**Comment by willykaram** [comment]
I think this issue was resolved last year. For the 2015 site, I've installed and configured both Mollom and Honeypot (ATM just for user registration, password reset and session submission). Once we decide if/where to enable comments, ratings or other user interactions, we may need to implement some solutions there.
