### ISSUE TITLE
Propose a Session - Other Info field, N/A

### ISSUE THREAD

**Issue by tz-earl** [NYC-Camp/website#51]
For the Other Info field, choosing the N/A radio button does not persist. When you go back to editing the form, the field has no value. The other values do persist.

Same problem with the Experience Level field. N/A does not stick, other values do.

**Comment by mirie** [comment]
@tz-earl,

I think this is the default behavior of the Drupal radio button field widget.

If we really want to ensure that none is _selected_ then this can be changed by using the select widget:

/admin/structure/types/manage/session/fields/field_session_other_info/widget-type
/admin/structure/types/manage/session/fields/field_experience/widget-type

Perhaps the Other Info field was set to radio buttons because the select list breaks the vertical menu? Personally, I would prefer getting rid of the vertical menu look and switching to the select list.

See the Other Info and Experience Level field values on: http://test-nyccamp2014.gotpantheon.com/node/530/edit. I changed the widget type for the Experience field.

**Comment by tz-earl** [comment]
@mirie I find the select list is clearer and more consistent in how it works. With the radio buttons I make a choice and expect it to be saved because N/A appears to be a valid value like all the others.

Another way to deal with this is that for Experience Level, add another choice "All Levels". For Other Info, add the choice "Other".

"Other Info" could be re-worded to "Kind of Session".

**Comment by jonpugh** [comment]
+1 to renaming "Other Info" to "Session Type". I would also rename the options so it just says "Training", "Lightning Talk", etc.

Make it required, and add a "Lecture" session type to be the default.

As for Experience level, add "All Levels" and make it required as well.

**Comment by ForestMars** [comment]
+1 rename "Other info" to "Session type" <-- (has cardinality of 1)
+1 requiring that field and Experience level. <-- (has cardinality >1)
+1 for adding "All levels" (++ @jonpugh)
I'm meh on "Lecture" and would prefer "Presentation"

**Comment by mirie** [comment]
Changes made on dev. Please review:

http://dev-nyccamp2014.gotpantheon.com/propose/session

**Comment by tz-earl** [comment]
Changes to widget types and wording look good, with more choices and better clarity.

**Comment by ForestMars** [comment]
"Session topics - medieval history" ?

Other than that, this looks fine. Please make the changes on Live and synch down to QA?

**Comment by tz-earl** [comment]
On test site, for content type Session, configured fields Session Type (previously Other Info) and Experience Level to be select lists, expanded their choices, and made both fields required. Needs review.  

http://test-nyccamp2014.gotpantheon.com/session/propose

**Edit: changed this from node/add/session to session/proposse**

**Comment by mirie** [comment]
Looks good!

**Comment by tz-earl** [comment]
Made the same configuration changes on live site to fields Session Type and Experience Level.

**Comment by ForestMars** [comment]
Just to note, I don't think we really need to do this twice (on Dev and then on Test.) 

Where things could break is actually more on the process and communication side. 

Totes appreciate the attention to doing it by the numbers, however configuration changes can really be made on Test, after confirming the db is synched up with Live, while the Dev environment is really for pushing changes in code. 

Great work going the extra mile!
