### ISSUE TITLE
Proposal: Continuously mirror the full github repo on Pantheon

### ISSUE THREAD

**Issue by jonpugh** [NYC-Camp/website#61]
Hi all,
I have a proposal.

We could remove a lot of the complexity of the workflow by simply continuously mirroring the github repo to pantheon.  This would mean that any commits and branches go directly to pantheon: Do not pass GO. Do not collect $200.

This would mean that we can just use pull requests, and when they are merged to master, it will go directly to the Dev site.  No more "upstream" vs. "pantheon" remotes. 

One repo is all you would ever care about.

I can set this up now using HubDrop.io  It is reliably mirroring over 100 drupal projects now, so it's pretty reliable.  

Would love to hear your thoughts.

**Comment by rabellamy** [comment]
Sounds good to me

**Comment by jmarkel** [comment]
Sounds good to me too. Seems to simplify things

I do want to hear Eric's thoughts though, since he's been the one doing the merges.

**Comment by rabellamy** [comment]
@mirie what do you think?

**Comment by esod** [comment]
Once a pr is merged to master, having it go directly to the Pantheon Dev site is a good idea. 

We're using Pantheon's multi-dev to develop functionality that we don't want in the master branch until the functionality is complete. The Personal Schedule feature, for instance, could conceivably be in the master branch because it's a self-contained features module. If the module is enabled, the menu tab is there; not enabled, no menu tab. no harm no foul. 

As another instance, we certainly (emphasis added on certainly) don't want something like cod_sans_og in the master branch until we are ready for it.

So I guess when I or someone merges to master, I will push it somewhere new, and it will be deployed to Pantheon dev automatically. That'll save me a step. +1

**Comment by mirie** [comment]
Yes, this sounds great. Thanks @jonpugh for creating this issue. I know it got lost in both irc and on skype the other day.

Also, when setting this up, can you add steps taken to the issue so that it's documented?

Thanks!

**Comment by willykaram** [comment]
We should be sure to a a quorum among at least get Tony, Mai, Eric, Forest and Elijah's on this issue. I'm trying to stay out of the fray on the web/dev workflow in order to focus on some of the other logistics of the camp as per the breakdown in Trello (venue, sponsorship, sprints, summits, trainings, food, design, travel, etc). You can see more on Jon's planet post here:

http://thinkdrop.net/blog-entry/february-26-2014-902am/introducing-hubdropio-bridging-gap-between-drupalorg-and-github

Any changes we make should be added to the workflow documentation: http://bit.ly/1fwdGwC . Going forward I won't have the time, to make the sort of updates we did last weekend, so someone else will need to take that.

Given that I'm trying to stay out of the fold, I'll happy to simply follow the team's lead/decisions on this.

**Comment by jonpugh** [comment]
@esod Just to be clear, all branches get mirrored, so multidev will still work fine.

**Comment by jmarkel** [comment]
Thanks for doing this, @jonpugh - a welcome simplification :-)

Let's make sure we keep the workflow documentation in sync too, so we don't
trip over our own feet. I had updated the README.md from the current
workflow doc in GDocs, but @ElijahLynn was going to follow up and do a full
wikify on it.

**Comment by jonpugh** [comment]
Ok. Here's the steps we gotta take:
- [x] Sync pantheon repo to github repo manually to ensure everything is in github.
- [x] Ensure hubdrop.io's SSH key is in my pantheon account so it can push.
- [x] I will add the bare git repo to hubdrop and configure it to pull from github and push to pantheon.
- [x] Push some test commits to GitHub and wait a few minutes to ensure it works.
- [ ] THEN switch the documentation to reflect the new setup.

I'd prefer to do this this weekend when there are as few hands on the code as possible.

**Comment by mirie** [comment]
Who are the remaining people who need to agree on this approach before we can move forward?

So far for YES, we have: @rabellamy, @esod, @jonpugh, @jmarkel, and me.

So from @willykaram's comment, it looks like we need: @ForestMars and/or @ElijahLynn.

Adding @robbiethegeek to this in case he wants to weigh in since he was on the workflow call.

**Comment by ForestMars** [comment]
++ for this. We're definitely getting important benefits from Github, but at the cost of a bifurcated workflow. I had planned to add a job that just pushed to Pantheon with the Github plugin for Jenkins, but, time. 

While I haven't given this enough consideration to get a sense of what's a better workflow, Jenkins autopushing to Pantheon when Github is pushed to, or Hubspot (which looks great, @jonpugh well done), I don't think that really matters for our immediate purposes. 

Thanks to Jon for the awesome tool and suggesting that we use it. and solid ++ to execute on this.

**Comment by jonpugh** [comment]
Thanks all.

Gonna set this up now.

**Comment by jonpugh** [comment]
Ok, its running.

Updates happen at most 4 minutes later... If you want it to happen quicker, http://gittip.com/hubdrop

Can someone please update the docs? 

THANKS!

**Comment by ForestMars** [comment]
Amazingly fast @jonpugh #WTG!

**Comment by rabellamy** [comment]
jonpugh++

**Comment by ForestMars** [comment]
"Can someone please update the docs?" 

@jmarkel Are you taking on doc updating, or is that whoever grabs it? I feel like it would be better to have a point person for documentation. Otherwise you have a gap in the process that hampers effective collaboration, bc no one is exactly sure who is doing what.

**Comment by jonpugh** [comment]
Confirmed that new branches make it to pantheon. It's technically feasible to set up almost instant pushes, but, you know, time. (Or money) 

Thanks for being my guinea pigs, guys.

**Comment by jonpugh** [comment]
I updated the README.md in the repo to reflect the change.  Calling it closed.
