### ISSUE TITLE
Connect Volunteer role with that mailchimp volunteer checkbox option

### ISSUE THREAD

**Issue by mirie** [NYC-Camp/website#62]
I don't think these are actually connected up properly.

**Background**

When a user _registers_ or _updates_ his/her user profile, there is either a checkbox on the register page or a local menu tab (user/%uid/mailchimp) for the mailchimp volunteer signup. The mailchimp volunteer list is setup here: /admin/config/services/mailchimp/lists/2/edit

However, when a user un/checks this volunteer option, this does not affect removing/assigning the volunteer role.

**What needs to be done**
We probably need a rule that links up removing/assigning the volunteer role with un/checking the mailchimp signup.

We probably also need to make the volunteer dashboard: admin/dashboard/volunteers available somewhere obviously visible in the navigation to users with the volunteer role. 

There is additional work needed for segmenting the mailchimp volunteer interests/availability appropriately.

**Comment by jonpugh** [comment]
What do we really need the Volunteer role for? Are there extra permissions they need to be granted?  Perhaps we don't need it at all. I don't think all volunteers need access to the volunteer dashboard page. I made that for my own use as the volunteer organizer last year.

I say let's just try to use the MailChimp text box to determine visibility of the Volunteer Info fieldset on the user profile form. I think this is what I did last year.

**Comment by ForestMars** [comment]
Roles are what is used to sync a user to a particular list on Mailchimp. Please note: 
1. I am not currently aware how to sync a user or set of users on the site to a Mailchimp list segment
   and
2.  We use segments where possible of the master attendee list, for reasons including that we are limited on the free tier to 2000 users total (ie. if joe user appears in 2 lists, he counts as 2 users toward our 2000.) 

Would _love_ a solution for #1 !

**Comment by jmarkel** [comment]
The Volunteer checkbox, far as I can tell, only goes to MC - it's not connected to any roles at all. If you check it, you're added to the MC Volunteer list. If it was checked and you uncheck it, MC is told to take you off the list. IIRC in neither case is a Drupal role added or removed.

**Comment by mirie** [comment]
Apparently we don't even have a Volunteer mailchimp list anymore. Was this a decision made by the group that didn't get communicated all around?

**Comment by ForestMars** [comment]
Yes, and I only found out belatedly myself. 

This was changed from a _list_ to a _list segment_ as we were waay over our free tier limits, and couldn't even send any mailings out at all. 

Our limits were only increased earlier today at 11am, from 2000 subscribers to 5000 subscribers, as well as an increase in how many mailings per month we can do. 

After the event is over, we will downgrade back to the free tier, so we really need to handling all lists as segments of our master list, so we will may have segments for example for "volunteers", "2013 attendees", "higher-ed summit members", etc. 

Having said that it does look like we will be moving to RedHen to handle the core functionality of our communications, and it should be noted that the same company that wrote RedHen also wrote the Mailchimp module (Thinkshout). 

@jmarkel Since we no longer have that list, can you please regression test that functionality and see what's going on there? 

Also, does anyone know if/how the mailchimp module handles synching to a list segment, and not a list? (I'm under the impression it may not actually handle that at all.)

**Comment by mirie** [comment]
Mailchimp does not handle synching to list _segments_ at this time. If we implement hook_mailchimp_process_webhook() then we can add users to a _group_ using the subscribe webhook (http://apidocs.mailchimp.com/webhooks/#subscribes).

Unfortunately, I'm not seeing the volunteer segment or group in the master list.

I unchecked 
- Show subscription options on the user registration form
- Show subscription options on the user registration form
- deselected the roles

( and selected the Drupal NYCCamp 2014 list in order to save the settings since a list is required)   on http://nyccamp.org/admin/config/services/mailchimp/lists/2/edit

This removes the Volunteer (newsletter) checkbox for the user registration and user edit forms. I removed them because currently they do nothing and also increase confusion since the selections are not saved anywhere.

The easiest way to proceed is to simply create a new list for 2014 volunteers (like before) and import the emails I aggregated for team@nyccamp.org. However, it sounds like you are moving forward with something new -- RedHen.

**Comment by mirie** [comment]
I also changed the Volunteer callout block on <front> -- I removed the mailchimp newsletter link because we don't have this setup anymore. I enabled my contact form for my profile and added a  link there. I tested this out and it works just as expected.

**Comment by mirie** [comment]
Closing this.
