### ISSUE TITLE
Pick a new universal hashtag for Drupal #NYCCamp

### ISSUE THREAD

**Issue by jonpugh** [NYC-Camp/website#67]
# nyccamp is not a specific enough hashtag. At this point there is only one photo of our NYC Camp in the block.  https://twitter.com/NYCCamp has been tweeting a lot.  A hashtag is supposed to be unique.

I don't think it's wise to compete for use of a hashtag. Let's just use #nyccampdrupal or something.

We should really change this. If there are photos from last years event they should be posted with a new hashtag so we can find them without lumping in unrelated photos.

**Comment by ForestMars** [comment]
Eh, My druthers would be to instead takeover this hashtag namespace. 

We could be doing a lot better on social media. If _everyone_ on the team just uploaded one picture to instagram, problem would be solved.

**Comment by likewhoa** [comment]
I agree with @ForestMars , instead of us being anti-social lets start being more social with our site marketing and use the social media venues which will get the word out to the masses. Everyone should at least post a twitter,instagram,failbook and or g+ posting regarding the camp and or work you've done on it that way the word spreads out. 

:-1: for closing this issue.

**Comment by jonpugh** [comment]
I updated the issue title and description to broaden it to the hashtag used on all things.  Let's get feedback from everyone. No one is stopping anyone from still using #nyccamp.  It would reduce confusion for our audience when searching for #nyccamp and finding lots of stuff that has nothing to do with us.

**Comment by willykaram** [comment]
@jonpugh our game plan is to keep growing the event and to own the #nyccamp hashtag. I would very much like us to continue on this path. We are also working to try and get the handle on Twitter. Can we close this issue and move it Trello or other forum, so that we keep the GitHub issues specific to the web development and coding efforts?

**Comment by ForestMars** [comment]
Worth noting that I just did a search for #nyccamp on twitter, and there was but a single unrelated tweet, which appeared to be a typo or something as it also had a non-working url. 

Looking forward to hearing what others think about this. It does seem however that the #nyccamp hashtag is only being used by us, despite the odd aberration we saw with those polynesia summer camp photos on Instagram. Still not sure what that was about. 

Having said that I think we can close this issue here as (1) We're not reaching a wide audience as this is just for devs actively working on the site, and (2) it doesn't seem like an issue that can be closed with a pull request, which I think is an implicit requirement the way we are using Github. 

My recommendation is that we move any discussion to Trello or in person meetings. So, boldly closing this here, but let's keep actively discussing how we are approaching our social media.
