### ISSUE TITLE
Add events blocks to events pages.

### ISSUE THREAD

**Issue by jonpugh** [NYC-Camp/website#68]
Once you click on an event, you are lost and must return to the homepage. http://nyccamp.org/event/git-training

Add the events block to all events pages.

**Comment by mirie** [comment]
How about we just keep that bar of event blocks on all pages on the site?

The blocks were configured to appear via the blocks admin:
- /admin/structure/block/manage/views/events_schedule_trainings-block/configure
- /admin/structure/block/manage/views/events_schedule_summits-block/configure
- /admin/structure/block/manage/views/events_schedule_sessions-block/configure
- /admin/structure/block/manage/views/events_schedule_sprints-block/configure

Originally the settings were:

```
Show Only the listed pages for:
<front>
user/register
user/login
```

Switched this to:  "All pages except those listed" and removed the paths

Please review on: http://dev-nyccamp2014.gotpantheon.com/

**Comment by jonpugh** [comment]
Looks awesome.

Escept on mobile, the events blocks are at the top and forces  user to
scroll way down to see anything... But it could be worse

**Comment by ForestMars** [comment]
Yes, I'm guessing it's going to be a fair amount of work to accordion the content in, so that the menu expands (pushDown?) and you can see the content you selected without having to scroll way down. 

Who's the resident jQuery ninja on the team that can weigh in on would be involved to do that? I suspect it may not be trivial, but it would be well worth it for mobile UX which is what people at actually going to be using at the event. 

cc @Snugug @timhobert @robbiethegeek

**Comment by timhobert** [comment]
On mobile we should just hide those events blocks on every page except the front page, IMO. With CSS.

**Comment by ForestMars** [comment]
Update: Just heard from Tim that he can fix this in the AM. 

edit: Just read Tim's comment. Hiding on all but the front page is exactly what Mai just changed it from.

**Comment by timhobert** [comment]
Hi All. I created a pull request that should clean up some things. It just needs approval an a push live. 
- Preview here: http://themeup-nyccamp2014.gotpantheon.com/
- Pull request here: https://github.com/NYC-Camp/website/pull/95/

Regarding the blue sidebars: Those can only appear on the front page. There is a region called "Aside" that can be used to add the events blocks (and any block for that matter) to the inner pages. That's what we did last year if I remember correctly. Yes, we may have to create duplicates of those event blocks, but that's what we did last year and that's how the theme is set up. (The theme has always been a moving target; like herding cats :)

I'm setting up the site now to have a blue sidebar-second (right sidebar) on the front page if we'd like one. Willy had requested this.

**Comment by timhobert** [comment]
Someone had added vertical tabs groups to the user profile fields (here: http://nyccamp.org/admin/config/people/accounts/fields ). I had to disable because it didn't look pretty on mobile. When my pull request in the above comment goes live there should be a bit of CSS cleanup included that makes the user profile page look nice without having vertical tabs.

**Comment by mirie** [comment]
Ok, based on what I'm reading here: We only want the event blocks to appear on the **front** page and no other pages. Or at least that is the current state on the site.

Can we agree to have something in the menu then, perhaps under About?

**Comment by willykaram** [comment]
@mirie I think that we should be keeping the events block in the left column on all pages (as per your suggestion above). In past year's that's the biggest issue we've had is confusion/questions around events/dates. In due course we can implement the accordion for this view -- I've opened a new issue for this here: https://github.com/NYC-Camp/website/issues/116

**Comment by mirie** [comment]
Great. Yes, I talked to @Sergey-Semashko about this and he has an idea for making this display nicely in the pull out menu on mobile.
